BTCPayServer/Models/ServerViewModels/RatesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Services.Rates;

namespace BTCPayServer.Models.ServerViewModels
{
    public class RatesViewModel
    {
        [Display(Name = "Bitcoin average api keys")]
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        [Display(Name = "Cache the rates for ... minutes")]
        [Range(0, 60)]
        public int CacheMinutes { get; set; }
        public GetRateLimitsResponse RateLimits { get; internal set; }
    }
}

BTCPayServer/Models/StoreViewModels/CheckoutExperienceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Services;
using BTCPayServer.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTCPayServer.Models.StoreViewModels
{
    public class CheckoutExperienceViewModel
    {
        class Format
        {
            public string Name { get; set; }
            public string Value { get; set; }
        }
        public SelectList CryptoCurrencies { get; set; }
        public SelectList Languages { get; set; }

        [Display(Name = "Default crypto currency on checkout")]
        public string DefaultCryptoCurrency { get; set; }
        [Display(Name = "Default language on checkout")]
        public string DefaultLang { get; set; }
        [Display(Name = "Do not propose lightning payment if value of the invoice is above...")]
        [MaxLength(20)]
        public string LightningMaxValue { get; set; }

        [Display(Name = "Requires a refund email")]
        public bool RequiresRefundEmail
        {
            get; set;
        }

        [Display(Name = "Do not propose on chain payment if the value of the invoice is below...")]
        [MaxLength(20)]
        public string OnChainMinValue { get; set; }

        [Display(Name = "Link to a custom CSS stylesheet")]
        [Uri]
        public string CustomCSS { get; set; }
        [Display(Name = "Link to a custom logo")]
        [Uri]
        public string CustomLogo { get; set; }

        [Display(Name = "Custom HTML title to display on Checkout page")]
        public string HtmlTitle { get; set; }


        public void SetCryptoCurrencies(ExplorerClientProvider explorerProvider, string defaultCrypto)
        {
            var choices = explorerProvider.GetAll().Select(o => new Format() { Name = o.Item1.CryptoCode, Value = o.Item1.CryptoCode }).ToArray();
            var chosen = choices.FirstOrDefault(f => f.Value == defaultCrypto) ?? choices.FirstOrDefault();
            CryptoCurrencies = new SelectList(choices, nameof(chosen.Value), nameof(chosen.Name), chosen);
            DefaultCryptoCurrency = chosen.Name;
        }

        public void SetLanguages(LanguageService langService, string defaultLang)
        {
            defaultLang = langService.GetLanguages().Any(language => language.Code == defaultLang)? defaultLang : "en";
            var choices = langService.GetLanguages().Select(o => new Format() { Name = o.DisplayName, Value = o.Code }).ToArray();
            var chosen = choices.FirstOrDefault(f => f.Value == defaultLang) ?? choices.FirstOrDefault();
            Languages = new SelectList(choices, nameof(chosen.Value), nameof(chosen.Name), chosen);
            DefaultLang = chosen.Value;
        }
    }
}

BTCPayServer/Models/StoreViewModels/PayButtonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BTCPayServer.Models.StoreViewModels
{
    public class PayButtonViewModel
    {
        public decimal Price { get; set; }
        public string InvoiceId { get; set; }
        [Required]
        public string Currency { get; set; }
        public string CheckoutDesc { get; set; }
        public string OrderId { get; set; }
        public int ButtonSize { get; set; }
        [Url]
        public string ServerIpn { get; set; }
        [Url]
        public string BrowserRedirect { get; set; }
        [EmailAddress]
        public string NotifyEmail { get; set; }

        public string StoreId { get; set; }

        // Data that influences Pay Button UI, but not invoice creation
        public string UrlRoot { get; set; }
        public List<string> CurrencyDropdown { get; set; }
        public string PayButtonImageUrl { get; set; }
    }
}

BTCPayServer/Models/StoreViewModels/RatesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Rating;
using BTCPayServer.Services.Rates;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTCPayServer.Models.StoreViewModels
{
    public class RatesViewModel
    {
        public class TestResultViewModel
        {
            public string CurrencyPair { get; set; }
            public string Rule { get; set; }
            public bool Error { get; set; }
        }
        class Format
        {
            public string Name { get; set; }
            public string Value { get; set; }
        }
        public void SetExchangeRates(CoinAverageExchange[] supportedList, string preferredExchange)
        {
            var defaultStore = preferredExchange ?? CoinAverageRateProvider.CoinAverageName;
            var choices = supportedList.Select(o => new Format() { Name = o.Display, Value = o.Name }).ToArray();
            var chosen = choices.FirstOrDefault(f => f.Value == defaultStore) ?? choices.FirstOrDefault();
            Exchanges = new SelectList(choices, nameof(chosen.Value), nameof(chosen.Name), chosen);
            PreferredExchange = chosen.Value;
        }

        public List<TestResultViewModel> TestRateRules { get; set; }

        public SelectList Exchanges { get; set; }

        public bool ShowScripting { get; set; }

        [Display(Name = "Rate rules")]
        [MaxLength(2000)]
        public string Script { get; set; }
        public string DefaultScript { get; set; }
        public string ScriptTest { get; set; }
        public CoinAverageExchange[] AvailableExchanges { get; set; }

        [Display(Name = "Add a spread on exchange rate of ... %")]
        [Range(0.0, 100.0)]
        public double Spread
        {
            get;
            set;
        }

        [Display(Name = "Preferred price source (eg. bitfinex, bitstamp...)")]
        public string PreferredExchange { get; set; }

        public string RateSource
        {
            get
            {
                return PreferredExchange == CoinAverageRateProvider.CoinAverageName ? "https://apiv2.bitcoinaverage.com/indices/global/ticker/short" : $"https://apiv2.bitcoinaverage.com/exchanges/{PreferredExchange}";
            }
        }
    }
}

BTCPayServer/Models/StoreViewModels/StoreUsersViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BTCPayServer.Models.StoreViewModels
{
    public class StoreUsersViewModel
    {
        public class StoreUserViewModel
        {
            public string Email { get; set; }
            public string Role { get; set; }
            public string Id { get; set; }
        }
        public StoreUsersViewModel()
        {
            Role = StoreRoles.Guest;
        }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string StoreId { get; set; }
        public string Role { get; set; }
        public List<StoreUserViewModel> Users { get; set; }
    }
}

BTCPayServer/Controllers/WalletsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using BTCPayServer.Data;
using BTCPayServer.HostedServices;
using BTCPayServer.ModelBinders;
using BTCPayServer.Models;
using BTCPayServer.Models.WalletViewModels;
using BTCPayServer.Security;
using BTCPayServer.Services;
using BTCPayServer.Services.Rates;
using BTCPayServer.Services.Stores;
using BTCPayServer.Services.Wallets;
using LedgerWallet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using NBitcoin;
using NBXplorer.DerivationStrategy;
using NBXplorer.Models;
using Newtonsoft.Json;
using static BTCPayServer.Controllers.StoresController;

namespace BTCPayServer.Controllers
{
    [Route("wallets")]
    [Authorize(AuthenticationSchemes = Policies.CookieAuthentication)]
    [AutoValidateAntiforgeryToken]
    public partial class WalletsController : Controller
    {
        public StoreRepository Repository { get; }
        public BTCPayNetworkProvider NetworkProvider { get; }
        public ExplorerClientProvider ExplorerClientProvider { get; }

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOptions<MvcJsonOptions> _mvcJsonOptions;
        private readonly NBXplorerDashboard _dashboard;

        private readonly IFeeProviderFactory _feeRateProvider;
        private readonly BTCPayWalletProvider _walletProvider;
        public RateFetcher RateFetcher { get; }
        [TempData]
        public string StatusMessage { get; set; }

        CurrencyNameTable _currencyTable;
        public WalletsController(StoreRepository repo,
                                 CurrencyNameTable currencyTable,
                                 BTCPayNetworkProvider networkProvider,
                                 UserManager<ApplicationUser> userManager,
                                 IOptions<MvcJsonOptions> mvcJsonOptions,
                                 NBXplorerDashboard dashboard,
                                 RateFetcher rateProvider,
                                 ExplorerClientProvider explorerProvider,
                                 IFeeProviderFactory feeRateProvider,
                                 BTCPayWalletProvider walletProvider)
        {
            _currencyTable = currencyTable;
            Repository = repo;
            RateFetcher = rateProvider;
            NetworkProvider = networkProvider;
            _userManager = userManager;
            _mvcJsonOptions = mvcJsonOptions;
            _dashboard = dashboard;
            ExplorerClientProvider = explorerProvider;
            _feeRateProvider = feeRateProvider;
            _walletProvider = walletProvider;
        }

        public async Task<IActionResult> ListWallets()
        {
            var wallets = new ListWalletsViewModel();
            var stores = await Repository.GetStoresByUserId(GetUserId());

            var onChainWallets = stores
                                .SelectMany(s => s.GetSupportedPaymentMethods(NetworkProvider)
                                              .OfType<DerivationStrategy>()
                                              .Select(d => ((Wallet: _walletProvider.GetWallet(d.Network),
                                                            DerivationStrategy: d.DerivationStrategyBase,
                                                            Network: d.Network)))
                                              .Where(_ => _.Wallet != null)
                                              .Select(_ => (Wallet: _.Wallet,
                                                            Store: s,
                                                            Balance: GetBalanceString(_.Wallet, _.DerivationStrategy),
                                                            DerivationStrategy: _.DerivationStrategy,
                                                            Network: _.Network)))
                                              .ToList();

            foreach (var wallet in onChainWallets)
            {
                ListWalletsViewModel.WalletViewModel walletVm = new ListWalletsViewModel.WalletViewModel();
                wallets.Wallets.Add(walletVm);
                walletVm.Balance = await wallet.Balance + " " + wallet.Wallet.Network.CryptoCode;
                if (!wallet.Store.HasClaim(Policies.CanModifyStoreSettings.Key))
                {
                    walletVm.Balance = "";
                }
                walletVm.CryptoCode = wallet.Network.CryptoCode;
                walletVm.StoreId = wallet.Store.Id;
                walletVm.Id = new WalletId(wallet.Store.Id, wallet.Network.CryptoCode);
                walletVm.StoreName = wallet.Store.StoreName;
                walletVm.IsOwner = wallet.Store.HasClaim(Policies.CanModifyStoreSettings.Key);
            }

            return View(wallets);
        }

        [HttpGet]
        [Route("{walletId}")]
        public async Task<IActionResult> WalletTransactions(
            [ModelBinder(typeof(WalletIdModelBinder))]
            WalletId walletId)
        {
            var store = await Repository.FindStore(walletId.StoreId, GetUserId());
            DerivationStrategy paymentMethod = GetPaymentMethod(walletId, store);
            if (paymentMethod == null)
                return NotFound();

            var wallet = _walletProvider.GetWallet(paymentMethod.Network);
            var transactions = await wallet.FetchTransactions(paymentMethod.DerivationStrategyBase);

            var model = new ListTransactionsViewModel();
            foreach (var tx in transactions.UnconfirmedTransactions.Transactions.Concat(transactions.ConfirmedTransactions.Transactions))
            {
                var vm = new ListTransactionsViewModel.TransactionViewModel();
                model.Transactions.Add(vm);
                vm.Id = tx.TransactionId.ToString();
                vm.Link = string.Format(CultureInfo.InvariantCulture, paymentMethod.Network.BlockExplorerLink, vm.Id);
                vm.Timestamp = tx.Timestamp;
                vm.Positive = tx.BalanceChange >= Money.Zero;
                vm.Balance = tx.BalanceChange.ToString();
                vm.IsConfirmed = tx.Confirmations != 0;
            }
            model.Transactions = model.Transactions.OrderByDescending(t => t.Timestamp).ToList();
            return View(model);
        }


        [HttpGet]
        [Route("{walletId}/send")]
        public async Task<IActionResult> WalletSend(
            [ModelBinder(typeof(WalletIdModelBinder))]
            WalletId walletId, string defaultDestination = null, string defaultAmount = null)
        {
            if (walletId?.StoreId == null)
                return NotFound();
            var store = await Repository.FindStore(walletId.StoreId, GetUserId());
            DerivationStrategy paymentMethod = GetPaymentMethod(walletId, store);
            if (paymentMethod == null)
                return NotFound();
            var network = this.NetworkProvider.GetNetwork(walletId?.CryptoCode);
            if (network == null)
                return NotFound();
            var storeData = store.GetStoreBlob();
            var rateRules = store.GetStoreBlob().GetRateRules(NetworkProvider);
            rateRules.Spread = 0.0m;
            var currencyPair = new Rating.CurrencyPair(paymentMethod.PaymentId.CryptoCode, GetCurrencyCode(storeData.DefaultLang) ?? "USD");
            WalletSendModel model = new WalletSendModel()
            {
                Destination = defaultDestination,
                CryptoCode = walletId.CryptoCode
            };
            if (double.TryParse(defaultAmount, out var amount))
                model.Amount = (decimal)amount;

            var feeProvider = _feeRateProvider.CreateFeeProvider(network);
            var recommendedFees = feeProvider.GetFeeRateAsync();
            var balance = _walletProvider.GetWallet(network).GetBalance(paymentMethod.DerivationStrategyBase);
            model.CurrentBalance = (await balance).ToDecimal(MoneyUnit.BTC);
            model.RecommendedSatoshiPerByte = (int)(await recommendedFees).GetFee(1).Satoshi;
            model.FeeSatoshiPerByte = model.RecommendedSatoshiPerByte;

            using (CancellationTokenSource cts = new CancellationTokenSource())
            {
                try
                {
                    cts.CancelAfter(TimeSpan.FromSeconds(5));
                    var result = await RateFetcher.FetchRate(currencyPair, rateRules).WithCancellation(cts.Token);
                    if (result.BidAsk != null)
                    {
                        model.Rate = result.BidAsk.Center;
                        model.Divisibility = _currencyTable.GetNumberFormatInfo(currencyPair.Right, true).CurrencyDecimalDigits;
                        model.Fiat = currencyPair.Right;
                    }
                    else
                    {
                        model.RateError = $"{result.EvaluatedRule} ({string.Join(", ", result.Errors.OfType<object>().ToArray())})";
                    }
                }
                catch (Exception ex) { model.RateError = ex.Message; }
            }
            return View(model);
        }

        [HttpPost]
        [Route("{walletId}/send")]
        public async Task<IActionResult> WalletSend(
            [ModelBinder(typeof(WalletIdModelBinder))]
            WalletId walletId, WalletSendModel vm)
        {
            if (walletId?.StoreId == null)
                return NotFound();
            var store = await Repository.FindStore(walletId.StoreId, GetUserId());
            if (store == null)
                return NotFound();
            var network = this.NetworkProvider.GetNetwork(walletId?.CryptoCode);
            if (network == null)

BTCPayServer/Views/Stores/CreateToken.cshtml
@model CreateTokenViewModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePageAndTitle(StoreNavPages.Tokens, "Create a new token");
    ViewBag.HidePublicKey = ViewBag.HidePublicKey ?? false;
    ViewBag.ShowStores = ViewBag.ShowStores ?? false;
}

<h4>@ViewData["Title"]</h4>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Label"></label>
                @if(ViewBag.HidePublicKey)
                {
                    <small class="text-muted">optional</small>
                }
                <input asp-for="Label" class="form-control" />
                <span asp-validation-for="Label" class="text-danger"></span>
            </div>
            @if(!ViewBag.HidePublicKey)
            {
                <div class="form-group">
                    <label asp-for="PublicKey"></label>
                    <small class="text-muted">Keep empty for server-initiated pairing</small>
                    <input asp-for="PublicKey" class="form-control" />
                    <span asp-validation-for="PublicKey" class="text-danger"></span>
                </div>}
            <div class="form-group">
                <label asp-for="Facade"></label>
                <select asp-for="Facade" class="form-control">
                    <option value="merchant">merchant</option>
                    <option value="pos">pos</option>
                </select>
                <span asp-validation-for="Facade" class="text-danger"></span>
            </div>

            @if(ViewBag.ShowStores)
            {
                <div class="form-group">
                    <label asp-for="StoreId" class="control-label"></label>
                    <select asp-for="StoreId" asp-items="Model.Stores" class="form-control"></select>
                    <span asp-validation-for="StoreId" class="text-danger"></span>
                </div>}
            else
            {
                <input type="hidden" asp-for="StoreId" />}
            <div class="form-group">
                <input type="submit" value="Request pairing" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

BTCPayServer/Views/Stores/UpdateStore.cshtml
@model StoreViewModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePageAndTitle(StoreNavPages.Index, "Profile");
}

<style type="text/css">
    .smMaxWidth {
        max-width: 150px;
    }

    @@media (min-width: 768px) {
        .smMaxWidth {
            max-width: 300px;
        }
    }
</style>


<h4>@ViewData["Title"]</h4>
<partial name="_StatusMessage" for="@TempData["TempDataProperty-StatusMessage"]" />

<div class="row">
    <div class="col-md-6">
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <form method="post">
            <div class="form-group">
                <label asp-for="Id"></label>
                <input asp-for="Id" readonly class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="StoreName"></label>
                <input asp-for="StoreName" class="form-control" />
                <span asp-validation-for="StoreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreWebsite"></label>
                <input asp-for="StoreWebsite" class="form-control" />
                <span asp-validation-for="StoreWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NetworkFee"></label>
                <a href="https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#add-network-fee-to-invoice-vary-with-mining-fees" target="_blank"><span class="fa fa-question-circle-o" title="More information..."></span></a>
                <input asp-for="NetworkFee" type="checkbox" class="form-check" />
            </div>
            <div class="form-group">
                <label asp-for="AnyoneCanCreateInvoice"></label>
                <a href="https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#allow-anyone-to-create-invoice" target="_blank"><span class="fa fa-question-circle-o" title="More information..."></span></a>
                <input asp-for="AnyoneCanCreateInvoice" type="checkbox" class="form-check" />
            </div>
            <div class="form-group">
                <label asp-for="InvoiceExpiration"></label>
                <a href="https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#invoice-expires-if-the-full-amount-has-not-been-paid-after-minutes" target="_blank"><span class="fa fa-question-circle-o" title="More information..."></span></a>
                <input asp-for="InvoiceExpiration" class="form-control" />
                <span asp-validation-for="InvoiceExpiration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonitoringExpiration"></label>
                <a href="https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#payment-invalid-if-transactions-fails-to-confirm-minutes-after-invoice-expiration" target="_blank"><span class="fa fa-question-circle-o" title="More information..."></span></a>
                <input asp-for="MonitoringExpiration" class="form-control" />
                <span asp-validation-for="MonitoringExpiration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentTolerance"></label>
                <a href="https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#consider-the-invoice-paid-even-if-the-paid-amount-is-less-than-expected" target="_blank"><span class="fa fa-question-circle-o" title="More information..."></span></a>
                <input asp-for="PaymentTolerance" class="form-control" />
                <span asp-validation-for="PaymentTolerance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeedPolicy"></label>
                <a href="https://docs.btcpayserver.org/faq-and-common-issues/faq-stores#consider-the-invoice-confirmed-when-the-payment-transaction" target="_blank"><span class="fa fa-question-circle-o" title="More information..."></span></a>
                <select asp-for="SpeedPolicy" class="form-control">
                    <option value="0">Is unconfirmed</option>
                    <option value="1">Has at least 1 confirmation</option>
                    <option value="3">Has at least 2 confirmations</option>
                    <option value="2">Has at least 6 confirmations</option>
                </select>
                <span asp-validation-for="SpeedPolicy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <h5>Derivation Scheme</h5>
                <span>The DerivationScheme represents the destination of the funds received by your invoice on chain.</span>
            </div>

            <div class="form-group">
                <table class="table table-sm table-responsive-md">
                    <thead>
                        <tr>
                            <th>Crypto</th>
                            <th>Derivation Scheme</th>
                            <th style="text-align:center;">Enabled</th>
                            <th style="text-align:right;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var scheme in Model.DerivationSchemes)
                        {
                            <tr>
                                <td>@scheme.Crypto</td>
                                <td class="smMaxWidth text-truncate">@scheme.Value</td>
                                <td style="text-align:center;">
                                    @if(scheme.Enabled)
                                    {
                                        <span class="fa fa-check"></span>
                                    }
                                    else
                                    {
                                        <span class="fa fa-times"></span>
                                    }
                                </td>
                                <td style="text-align:right">
                                    @if(!string.IsNullOrWhiteSpace(scheme.Value))
                                    {
                                        <a asp-action="WalletTransactions" asp-controller="Wallets" asp-route-walletId="@scheme.WalletId">Wallet</a><span> - </span>
                                    }
                                    <a asp-action="AddDerivationScheme" asp-route-cryptoCode="@scheme.Crypto">Modify</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="form-group">
                <div class="form-group">
                    <h5>Lightning nodes (Experimental)</h5>
                    <p>
                        <span>A connection to a lightning charge node is required to generate lightning network enabled invoices.<br /></span>
                        <span>This is experimental and not advised for production.</span>
                    </p>
                </div>
                <div class="form-group">
                    <table class="table table-sm table-responsive-md">
                        <thead>
                            <tr>
                                <th>Crypto</th>
                                <th>Address</th>
                                <th style="text-align:center;">Enabled</th>
                                <th style="text-align:right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var scheme in Model.LightningNodes)
                            {
                                <tr>
                                    <td>@scheme.CryptoCode</td>
                                    <td class="smMaxWidth text-truncate">@scheme.Address</td>
                                    <td style="text-align:center;">
                                        @if(scheme.Enabled)
                                        {
                                            <span class="fa fa-check"></span>
                                        }
                                        else
                                        {
                                            <span class="fa fa-times"></span>
                                        }
                                    </td>
                                    <td style="text-align:right"><a asp-action="AddLightningNode" asp-route-cryptoCode="@scheme.CryptoCode">Modify</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="LightningDescriptionTemplate"></label>
                <input asp-for="LightningDescriptionTemplate" class="form-control" />
                <span asp-validation-for="LightningDescriptionTemplate" class="text-danger"></span>
                <p class="form-text text-muted">
                    Available placeholders are: {StoreName}, {ItemDescription} and {OrderId}
                </p>
            </div>
            
             <div class="form-group">
                <div class="form-group">
                    <h5>Third party Payment methods</h5>
                </div>
                <div class="form-group">
                    <table class="table table-sm table-responsive-md">
                        <thead>
                            <tr>
                                <th>Provider</th>
                                <th style="text-align:center;">Enabled</th>
                                <th style="text-align:right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach(var scheme in Model.ThirdPartyPaymentMethods)
                        {
                            <tr>
                                <td>@scheme.Provider</td>
                                <td style="text-align:center;">
                                    @if(scheme.Enabled)
                                    {
                                        <span class="fa fa-check"></span>
                                    }
                                    else
                                    {
                                        <span class="fa fa-times"></span>
                                    }
                                </td>
                                <td style="text-align:right"><a asp-action="@scheme.Action" >Modify</a></td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
            
            @if(Model.CanDelete)
            {
                <div class="form-group">
                    <h5>Other actions...</h5>
                    <p><a href="#danger-zone" data-toggle="collapse"><b>Click here to see more actions</b></a></p>
                    <div id="danger-zone" class="collapse">
                        <a class="btn btn-outline-danger form-control" asp-action="DeleteStore" asp-route-storeId="@Model.Id">Delete this store</a>
                    </div>
                </div>
            }
            <button name="command" type="submit" class="btn btn-primary" value="Save">Save</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}