BTCPayServer/Models/WalletViewModels/ListWalletsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BTCPayServer.Models.WalletViewModels
{
    public class ListWalletsViewModel
    {
        public class WalletViewModel
        {
            public string StoreName { get; set; }
            public string StoreId { get; set; }
            public string CryptoCode { get; set; }
            public string Balance { get; set; }
            public bool IsOwner { get; set; }
            public WalletId Id { get; set; }
        }

        public List<WalletViewModel> Wallets { get; set; } = new List<WalletViewModel>();
    }
}

BTCPayServer/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BTCPayServer.Authentication;
using BTCPayServer.Configuration;
using BTCPayServer.Data;
using BTCPayServer.Models;
using BTCPayServer.Models.AppViewModels;
using BTCPayServer.Models.StoreViewModels;
using BTCPayServer.Payments.Changelly;
using BTCPayServer.Rating;
using BTCPayServer.Security;
using BTCPayServer.Services;
using BTCPayServer.Services.Rates;
using BTCPayServer.Services.Stores;
using BTCPayServer.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using NBitcoin;
using NBitcoin.DataEncoders;

namespace BTCPayServer.Controllers
{
    [Route("stores")]
    [Authorize(AuthenticationSchemes = Policies.CookieAuthentication)]
    [Authorize(Policy = Policies.CanModifyStoreSettings.Key)]
    [AutoValidateAntiforgeryToken]
    public partial class StoresController : Controller
    {
        RateFetcher _RateFactory;
        public string CreatedStoreId { get; set; }
        public StoresController(
            IServiceProvider serviceProvider,
            BTCPayServerOptions btcpayServerOptions,
            BTCPayServerEnvironment btcpayEnv,
            StoreRepository repo,
            TokenRepository tokenRepo,
            UserManager<ApplicationUser> userManager,
            AccessTokenController tokenController,
            BTCPayWalletProvider walletProvider,
            BTCPayNetworkProvider networkProvider,
            RateFetcher rateFactory,
            ExplorerClientProvider explorerProvider,
            IFeeProviderFactory feeRateProvider,
            LanguageService langService,
            ChangellyClientProvider changellyClientProvider,
            IOptions<MvcJsonOptions> mvcJsonOptions,
            IHostingEnvironment env, IHttpClientFactory httpClientFactory)
        {
            _RateFactory = rateFactory;
            _Repo = repo;
            _TokenRepository = tokenRepo;
            _UserManager = userManager;
            _LangService = langService;
            _changellyClientProvider = changellyClientProvider;
            MvcJsonOptions = mvcJsonOptions;
            _TokenController = tokenController;
            _WalletProvider = walletProvider;
            _Env = env;
            _httpClientFactory = httpClientFactory;
            _NetworkProvider = networkProvider;
            _ExplorerProvider = explorerProvider;
            _FeeRateProvider = feeRateProvider;
            _ServiceProvider = serviceProvider;
            _BtcpayServerOptions = btcpayServerOptions;
            _BTCPayEnv = btcpayEnv;
        }
        BTCPayServerOptions _BtcpayServerOptions;
        BTCPayServerEnvironment _BTCPayEnv;
        IServiceProvider _ServiceProvider;
        BTCPayNetworkProvider _NetworkProvider;
        private ExplorerClientProvider _ExplorerProvider;
        private IFeeProviderFactory _FeeRateProvider;
        BTCPayWalletProvider _WalletProvider;
        AccessTokenController _TokenController;
        StoreRepository _Repo;
        TokenRepository _TokenRepository;
        UserManager<ApplicationUser> _UserManager;
        private LanguageService _LangService;
        private readonly ChangellyClientProvider _changellyClientProvider;
        IHostingEnvironment _Env;
        private IHttpClientFactory _httpClientFactory;

        [TempData]
        public string StatusMessage
        {
            get; set;
        }

        [HttpGet]
        [Route("{storeId}/users")]
        public async Task<IActionResult> StoreUsers()
        {
            StoreUsersViewModel vm = new StoreUsersViewModel();
            await FillUsers(vm);
            return View(vm);
        }

        private async Task FillUsers(StoreUsersViewModel vm)
        {
            var users = await _Repo.GetStoreUsers(StoreData.Id);
            vm.StoreId = StoreData.Id;
            vm.Users = users.Select(u => new StoreUsersViewModel.StoreUserViewModel()
            {
                Email = u.Email,
                Id = u.Id,
                Role = u.Role
            }).ToList();
        }

        public StoreData StoreData
        {
            get
            {
                return this.HttpContext.GetStoreData();
            }
        }


        [HttpPost]
        [Route("{storeId}/users")]
        public async Task<IActionResult> StoreUsers(StoreUsersViewModel vm)
        {
            await FillUsers(vm);
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            var user = await _UserManager.FindByEmailAsync(vm.Email);
            if (user == null)
            {
                ModelState.AddModelError(nameof(vm.Email), "User not found");
                return View(vm);
            }
            if (!StoreRoles.AllRoles.Contains(vm.Role))
            {
                ModelState.AddModelError(nameof(vm.Role), "Invalid role");
                return View(vm);
            }
            if (!await _Repo.AddStoreUser(StoreData.Id, user.Id, vm.Role))
            {
                ModelState.AddModelError(nameof(vm.Email), "The user already has access to this store");
                return View(vm);
            }
            StatusMessage = "User added successfully";
            return RedirectToAction(nameof(StoreUsers));
        }

        [HttpGet]
        [Route("{storeId}/users/{userId}/delete")]
        public async Task<IActionResult> DeleteStoreUser(string userId)
        {
            StoreUsersViewModel vm = new StoreUsersViewModel();
            var user = await _UserManager.FindByIdAsync(userId);
            if (user == null)
                return NotFound();
            return View("Confirm", new ConfirmModel()
            {
                Title = $"Remove store user",
                Description = $"Are you sure to remove access to remove access to {user.Email}?",
                Action = "Delete"
            });
        }

        [HttpPost]
        [Route("{storeId}/users/{userId}/delete")]
        public async Task<IActionResult> DeleteStoreUserPost(string storeId, string userId)
        {
            await _Repo.RemoveStoreUser(storeId, userId);
            StatusMessage = "User removed successfully";
            return RedirectToAction(nameof(StoreUsers), new { storeId = storeId, userId = userId });
        }

        [HttpGet]
        [Route("{storeId}/rates")]
        public IActionResult Rates()
        {
            var storeBlob = StoreData.GetStoreBlob();
            var vm = new RatesViewModel();
            vm.SetExchangeRates(GetSupportedExchanges(), storeBlob.PreferredExchange ?? CoinAverageRateProvider.CoinAverageName);
            vm.Spread = (double)(storeBlob.Spread * 100m);
            vm.Script = storeBlob.GetRateRules(_NetworkProvider).ToString();
            vm.DefaultScript = storeBlob.GetDefaultRateRules(_NetworkProvider).ToString();
            vm.AvailableExchanges = GetSupportedExchanges();
            vm.ShowScripting = storeBlob.RateScripting;
            return View(vm);
        }

        [HttpPost]
        [Route("{storeId}/rates")]
        public async Task<IActionResult> Rates(RatesViewModel model, string command = null)
        {
            model.SetExchangeRates(GetSupportedExchanges(), model.PreferredExchange);
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.PreferredExchange != null)
                model.PreferredExchange = model.PreferredExchange.Trim().ToLowerInvariant();

            var blob = StoreData.GetStoreBlob();
            model.DefaultScript = blob.GetDefaultRateRules(_NetworkProvider).ToString();
            model.AvailableExchanges = GetSupportedExchanges();

            blob.PreferredExchange = model.PreferredExchange;
            blob.Spread = (decimal)model.Spread / 100.0m;

            if (!model.ShowScripting)
            {
                if (!GetSupportedExchanges().Select(c => c.Name).Contains(blob.PreferredExchange, StringComparer.OrdinalIgnoreCase))
                {
                    ModelState.AddModelError(nameof(model.PreferredExchange), $"Unsupported exchange ({model.RateSource})");
                    return View(model);
                }
            }
            RateRules rules = null;
            if (model.ShowScripting)
            {
                if (!RateRules.TryParse(model.Script, out rules, out var errors))
                {
                    errors = errors ?? new List<RateRulesErrors>();
                    var errorString = String.Join(", ", errors.ToArray());
                    ModelState.AddModelError(nameof(model.Script), $"Parsing error ({errorString})");
                    return View(model);
                }
                else
                {
                    blob.RateScript = rules.ToString();
                    ModelState.Remove(nameof(model.Script));
                    model.Script = blob.RateScript;
                }
            }
            rules = blob.GetRateRules(_NetworkProvider);

            if (command == "Test")
            {
                if (string.IsNullOrWhiteSpace(model.ScriptTest))
                {
                    ModelState.AddModelError(nameof(model.ScriptTest), "Fill out currency pair to test for (like BTC_USD,BTC_CAD)");
                    return View(model);
                }
                var splitted = model.ScriptTest.Split(',', StringSplitOptions.RemoveEmptyEntries);

                var pairs = new List<CurrencyPair>();
                foreach (var pair in splitted)
                {
                    if (!CurrencyPair.TryParse(pair, out var currencyPair))
                    {

BTCPayServer/Views/Wallets/ListWallets.cshtml
@model BTCPayServer.Models.WalletViewModels.ListWalletsViewModel
@{
    ViewData["Title"] = "Wallets";
}

<section>
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <partial name="_StatusMessage" for="@TempData["TempDataProperty-StatusMessage"]" />
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">@ViewData["Title"]</h2>
                <hr class="primary">
                <p>Create and manage wallets.</p>
            </div>
        </div>

        <div class="row">
            <table class="table table-sm table-responsive-md">
                <thead>
                    <tr>
                        <th>Store Name</th>
                        <th>Crypto Code</th>
                        <th>Balance</th>
                        <th style="text-align:right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var wallet in Model.Wallets)
                    {
                    <tr>
                        @if(wallet.IsOwner)
                        {
                            <td><a asp-action="UpdateStore" asp-controller="Stores" asp-route-storeId="@wallet.StoreId">@wallet.StoreName</a></td>
                        }
                        else
                        {
                            <td>@wallet.StoreName</td>
                        }
                        <td>@wallet.CryptoCode</td>
                        <td>@wallet.Balance</td>
                        <td style="text-align:right">
                            <a asp-action="WalletTransactions" asp-route-walletId="@wallet.Id">Manage</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

BTCPayServer/Views/Wallets/WalletRescan.cshtml
@model RescanWalletModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData["Title"] = "Rescan wallet";
    ViewData.SetActivePageAndTitle(WalletsNavPages.Rescan);
}

<h4>@ViewData["Title"]</h4>

@if (!Model.Ok)
{
    <div class="row">
        <div class="col-md-10">
            <p>This feature is disabled</p>
            @if (Model.IsFullySync)
            {
                <p><span class="fa fa-check-circle" style="color:green;"></span> <span>The full node is synched</span></p>
            }
            else
            {
                <p><span class="fa fa-times-circle" style="color:red;"></span> <span>The full node is not synched</span></p>
            }
            @if (Model.IsServerAdmin)
            {
                <p><span class="fa fa-check-circle" style="color:green;"></span> <span>You are server administrator</span></p>
            }
            else
            {
                <p><span class="fa fa-times-circle" style="color:red;"></span> <span>You are not server administrator</span></p>
            }
            @if (Model.IsSupportedByCurrency)
            {
                <p><span class="fa fa-check-circle" style="color:green;"></span> <span>This full node support rescan of the UTXO set</span></p>
            }
            else
            {
                <p><span class="fa fa-times-circle" style="color:red;"></span> <span>This full node do not support rescan of the UTXO set</span></p>
            }
            @if (Model.IsSegwit)
            {
                <p><span class="fa fa-check-circle" style="color:green;"></span> <span>This wallet is compatible with segwit</span></p>
            }
            else
            {
                <p><span class="fa fa-times-circle" style="color:red;"></span> <span>This wallet is not compatible with segwit</span></p>
            }
        </div>
    </div>
}
else if (!Model.Progress.HasValue)
{
    <div class="row">
        @if (Model.PreviousError != null)
        {
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span>The previous scan stopped with an error: @Model.PreviousError</span>
            </div>
        }
        else if (Model.LastSuccess != null)
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span>The previous scan completed and found <b>@Model.LastSuccess.Found</b> UTXOs in <b>@Model.TimeOfScan</b> (The total UTXO set size is @Model.LastSuccess.TotalSizeOfUTXOSet.Value)</span>
            </div>
        }
        <div class="col-md-10">
            <p>
                Scanning the UTXO set allow you to restore the balance of your wallet, but not all the transaction history.
            </p>
            <p>
                This operation will scan the HD Path <b>0/*</b>, <b>1/*</b> and <b>*</b> from a starting index, until no UTXO are found in a whole gap limit.
            </p>
            <p>The batch size make sure the scan do not consume too much RAM at once by rescanning several time with smaller subset of addresses.</p>
            <p>If you do not understand above, just keep the default values and click on <b>Start Scan</b></p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <form method="post">
                <div class="form-group">
                    <label asp-for="StartingIndex"></label>
                    <input asp-for="StartingIndex" class="form-control" type="number" />
                </div>
                <div class="form-group">
                    <label asp-for="GapLimit"></label>
                    <input asp-for="GapLimit" class="form-control" type="number" />
                </div>
                <div class="form-group">
                    <label asp-for="BatchSize"></label>
                    <input asp-for="BatchSize" class="form-control" type="number" />
                </div>
                <button type="submit" class="btn btn-primary">Start scan</button>
            </form>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-10">
            <p>Scanning in progress, refresh the page to see the progress... (Estimated time: @Model.RemainingTime)</p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@(Model.Progress.Value)"
                     aria-valuemin="0" aria-valuemax="100" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; width:@(Model.Progress.Value)%;">
                    @(Model.Progress.Value)% (estimated time: @Model.RemainingTime)
                </div>
            </div>
        </div>
    </div>
}

BTCPayServer/Views/Wallets/WalletSend.cshtml
@model WalletSendModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData["Title"] = "Manage wallet";
    ViewData.SetActivePageAndTitle(WalletsNavPages.Send);
}

<h4>@ViewData["Title"]</h4>

<div class="row">
    <div class="col-md-10">
        <p>
            Send funds to a destination address.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <input type="hidden" asp-for="Divisibility" />
            <input type="hidden" asp-for="Fiat" />
            <input type="hidden" asp-for="Rate" />
            <input type="hidden" asp-for="CurrentBalance" />
            <input type="hidden" asp-for="RecommendedSatoshiPerByte" />
            <input type="hidden" asp-for="CryptoCode" />

            <div class="form-group">
                <label asp-for="Destination"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount"></label>
                <div class="input-group">
                    <input asp-for="Amount" class="form-control" onkeyup='updateFiatValue();' />
                    <div class="input-group-prepend">
                        <span class="input-group-text text-muted" style="display:none;" id="fiatValue"></span>
                    </div>
                </div>
                <span asp-validation-for="Amount" class="text-danger"></span>
                <p class="form-text text-muted crypto-info">
                    Your current balance is <a id="crypto-balance-link" href="#"><span>@Model.CurrentBalance</span></a> <span>@Model.CryptoCode</span>.
                </p>
            </div>
            <div class="form-group">
                <label asp-for="FeeSatoshiPerByte"></label>
                <input asp-for="FeeSatoshiPerByte" class="form-control" />
                <span id="FeeRate-Error" class="text-danger"></span>
                <p class="form-text text-muted crypto-info">
                    The recommended value is <a id="crypto-fee-link" href="#"><span>@Model.RecommendedSatoshiPerByte</span></a> satoshi per byte.
                </p>
            </div>
            <div class="form-group">
                <label asp-for="SubstractFees"></label>
                <input asp-for="SubstractFees" class="form-check" />
            </div>
            <button type="submit" class="btn btn-primary">Confirm</button>
        </form>
    </div>
</div>
@section Scripts
{
    <script src="~/js/WalletSend.js" type="text/javascript" defer="defer"></script>
}

BTCPayServer/Views/Wallets/WalletSendLedger.cshtml
@model WalletSendLedgerModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData["Title"] = "Manage wallet";
    ViewData.SetActivePageAndTitle(WalletsNavPages.Send);
}

<h4>Sign the transaction with Ledger</h4>
<div id="walletAlert" class="alert alert-danger alert-dismissible" style="display:none;" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span id="alertMessage"></span>
</div>
<div class="row">
    <div class="col-md-10">
        <input type="hidden" asp-for="Destination" />
        <input type="hidden" asp-for="Amount" />
        <input type="hidden" asp-for="FeeSatoshiPerByte" />
        <input type="hidden" asp-for="SubstractFees" />
        <p>
            You can send money received by this store to an address with the help of your Ledger Wallet. <br />
            If you don't have a Ledger Wallet, use Electrum with your favorite hardware wallet to transfer crypto. <br />
            If your Ledger wallet is not detected:
        </p>
        <ul>
            <li>Make sure you are running the Ledger app with version superior or equal to 1.2.4</li>
            <li>Use Google Chrome browser and open the coin app on your Ledger</li>
        </ul>
        <p id="hw-loading"><span class="fa fa-question-circle" style="color:orange"></span> <span>Detecting hardware wallet...</span></p>
        <p id="hw-error" style="display:none;"><span class="fa fa-times-circle" style="color:red;"></span> <span class="hw-label">An error happened</span></p>
        <p id="hw-success" style="display:none;"><span class="fa fa-check-circle" style="color:green;"></span> <span class="hw-label">Detecting hardware wallet...</span></p>

        <p id="check-loading" style="display:none;"><span class="fa fa-question-circle" style="color:orange"></span> <span class="check-label">Detecting hardware wallet...</span></p>
        <p id="check-error" style="display:none;"><span class="fa fa-times-circle" style="color:red;"></span> <span class="check-label">An error happened</span></p>
        <p id="check-success" style="display:none;"><span class="fa fa-check-circle" style="color:green;"></span> <span class="check-label">Detecting hardware wallet...</span></p>
    </div>
</div>


@section Scripts
{
    <script src="~/js/ledgerwebsocket.js" type="text/javascript" defer="defer"></script>
    <script src="~/js/WalletSendLedger.js" type="text/javascript" defer="defer"></script>
}

BTCPayServer/Views/Wallets/WalletTransactions.cshtml
@model ListTransactionsViewModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData["Title"] = "Manage wallet";
    ViewData.SetActivePageAndTitle(WalletsNavPages.Transactions);
}

<style type="text/css">
    .smMaxWidth {
        max-width: 200px;
    }

    @@media (min-width: 768px) {
        .smMaxWidth {
            max-width: 400px;
        }
    }

    .unconf {
        opacity: 0.5;
    }
</style>

<div class="row">
    <div class="col-md-10 text-center">
        <partial name="_StatusMessage" for="@TempData["TempDataProperty-StatusMessage"]" />
    </div>
</div>
<h4>@ViewData["Title"]</h4>
<div class="row">
    <div class="col-md-10">
        If this wallet got restored, should have received money but nothing is showing up, please <a asp-action="WalletRescan">Rescan it</a>.
    </div>
</div>
<div class="row">
    <div class="col-md-10">
        <table class="table table-sm table-responsive-lg">
            <thead class="thead-inverse">
                <tr>
                    <th>Timestamp</th>
                    <th>Transaction Id</th>
                    <th style="text-align:right">Balance</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var transaction in Model.Transactions)
                {
                    <tr class="@(transaction.IsConfirmed ? "" : "unconf")">
                        <td>@transaction.Timestamp.ToTimeAgo()</td>
                        <td class="smMaxWidth text-truncate">
                            <a href="@transaction.Link" target="_blank">
                                @transaction.Id
                            </a>
                        </td>
                        @if (transaction.Positive)
                        {
                            <td style="text-align:right; color:green;">@transaction.Balance</td>
                        }
                        else
                        {
                            <td style="text-align:right; color:red;">@transaction.Balance</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BTCPayServer/Views/Wallets/_Nav.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<div class="nav flex-column nav-pills">
    <a class="nav-link @ViewData.IsActivePage(WalletsNavPages.Transactions)" asp-action="WalletTransactions">Transactions</a>
    <a class="nav-link @ViewData.IsActivePage(WalletsNavPages.Send)" asp-action="WalletSend">Send</a>
    <a class="nav-link @ViewData.IsActivePage(WalletsNavPages.Rescan)" asp-action="WalletRescan">Rescan</a>
</div>